export const white = '#fff'
export const red = '#801515'
export const gray = '#333'
export const lightGray = '#777'
export const lightRed = '#ffaaaa'
export const green = '#158015'
export const lightGreen = '#aaffaa'